### ISSUE TITLE
Question: How do I make the width of the output table smaller? And how do I get coloring in my output?

### ISSUE THREAD

**Issue by louwjlabuschagne** [mtxr/SQLTools#105]
> This is a guideline to help us to understand SQLTools Issues. 
> 
> You don't need to stick to this, but please try to guide us to reproduce the errors or understand your feature requests.

### Issue Type

* [ ] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Prerequisites (For bugfixes)

* [ ] Are you running the latest version?
* [ ] Did you check the logs?
* [ ] Did you check the Setup?

### Description

[Description of the bug or feature]

### Steps to Reproduce (For bugfixes)

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

- *Version*: vX.Y.Z
- *OS*: ...
- *RDBMS*: (MySQL, PostgreSQL, Oracle, MSSQL, SQLite, Vertica, ...)

You can get this information from executing `ST: About` from Sublime `Command Palette`.

**Comment by tkopets** [comment]
1. SQLTools shows the output from DB CLI, so if there is an option to reduce the output width in your RDBMS-specific DB CLI you can tweak that, otherwise not.
*What RDBMS are you using?*
2. There is no support for colored output in SQLTools, but I'm just curious what exactly do you expect in terms of coloring of output?
I guess the only possibility to color the output might be tweaking the code to use a special syntax highlighting.

**Comment by tkopets** [comment]
SQL syntax highlighting is used when you invoke SQLTools commands `Table Description` and `Function Description`.
See this related issue: #84

**Comment by tkopets** [comment]
Closing this issue.
It does not contain a meaningful description and lacks follow-up feedback.
