### ISSUE TITLE
Can't connect in mysql if don't have password

### ISSUE THREAD

**Issue by matheushenrique** [mtxr/SQLTools#11]
I couldn't access the database, i have without a password in my local, my solution was rewrite in sublime-settings - User deleting the -p\"{password}\" argument but I think you should include that case in the default settings

**Comment by mtxr** [comment]
Actually I think it's better to keep password as default.

Usually databases has passwords for security and most of users use it.

The idea of overriding the sublime-settings is to customize it to your needs.
I'll keep the issue opened. In case a lot of people request this "feature" I can change it.

**Comment by rpbaptist** [comment]
I had the same issue in https://github.com/mtxr/SQLTools/issues/66

I don't use a password for my local development database. Once someone has full access to my machine the development database is the least of my worries.

**Comment by tkopets** [comment]
E.g. edit your `SQLToolsConnections.sublime-settings` to something like this:
```json
{
    "connections": {
        "MySQL Connetion without Pasword": {
            "type"    : "mysql",
            "host"    : "localhost",
            "port"    :  3306,
            "username": "root",
            // remove or comment out the password field
            "database": "sakila",
            "encoding": "utf-8"
        }
    }
}
```

**Comment by rpbaptist** [comment]
That didn't work because the mysql connection line still supplies the `-p` flag for the password. I changed it as specified by @matheushenrique .

**Comment by tkopets** [comment]
@rpbaptist 
It is not required in the latest version of SQLTools - most probably you have custom config overriding the defaults - that's why it is not working for you.
For best experience I would **highly recommend** that you edit your `User\SQLTools.sublime-settings` and leave only those settings that you want to override.
If you don't then most probably most of the newly developed functionality (smart completions, optional passwords, alternative auth-methods, etc) will not work for you.
Please let me know if that solves your problem.

**Comment by rpbaptist** [comment]
@tkopets Thanks. That worked. I had indeed copied the old settings and made adjustments. I removed most of it now.

**Comment by tkopets** [comment]
Awesome!
