### ISSUE TITLE
Show execution status on the status bar

### ISSUE THREAD

**Issue by ngr-t** [mtxr/SQLTools#130]
### Issue Type

* [x] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [ ] Other

### Description

I think it's helpful to show if a query is under execution in the status bar. Maybe we don't have that kind of thing now. I imagine of one with text animation like `Package Control` has, but just texts like "busy" or something should be OK.

I'll make a PR for this if you think it a good feature.

### Versions

- *Version*: v0.9.4
- *OS*: Mac OS X
- *RDBMS*: MySQL

**Comment by Coteh** [comment]
I was looking into this sort of feature not too long ago actually, and as I was taking a look at the codebase, I noticed that [there already is a status message implemented.](https://github.com/mtxr/SQLTools/blob/a787d4ff1cb7390c838b1732957295ea724d5d0e/SQLTools.py#L472) However, it never seemed to show up for me. Then I found out that what seems to be happening is that [the status message clear call on this line](https://github.com/mtxr/SQLTools/blob/a787d4ff1cb7390c838b1732957295ea724d5d0e/SQLTools.py#L119) is clearing out the status message before it appears on the screen. This can be observed by commenting out said line, saving, then reexecuting command once plugin reloads.
I am not sure what the best solution to this problem is at this time, but I just thought that I at least bring this to your attention before you work on this feature. Perhaps the Command thread is running the createOutput callback before it actually finishes the query? That's my best guess at the moment.

An animation for the status bar like the one in Package Control would be really cool and I would find it very helpful to have an indicator of progress that stands out on the UI when running a query.

**Comment by ngr-t** [comment]
Thank you for advice!
I'll look into a good fix for this.

**Comment by tkopets** [comment]
It used to work a while ago, but with the addition of recent functionality, it is now broken.
I will fix it so it works as it used to work before.
Feel free to improve it.

**Comment by ngr-t** [comment]
Thank you for fixing!
I think of adding animation, but not very soon (so sorry but I'm little busy now). Therefore I close this issue for now.
