### ISSUE TITLE
syntax SQL

### ISSUE THREAD

**Issue by mercurykd** [mtxr/SQLTools#158]
best extension!
You can make the syntax do not change in result tab?

And ctrl+e+s show result not in utf-8 and columns in the table shifted....
my settings:
```
"show_result_on_window": true,
"clear_output": false,
"cli_options": {
        "mysql": {
            "options": ["-f", "--table","--default-character-set=utf8"],
        }
    }
```

**Comment by tkopets** [comment]
Thanks @mercurykd !
It is best to create a separate issue for each of your requests.

Regarding **syntax change**:
`ST: Describe Table` and `ST: Describe Function` are using SQL syntax (if your main syntax is also SQL-related) because SQL is expected in the output, otherwise, we use `Plain Text` syntax to show all other output, because `Plain Text` performs much better for long output.
Also, see #84 
Maybe I didn't fully understand your request regarding syntax change, so feel free to explain it in more details (images & gifs are welcome).

Regarding **shifted columns issue**:
I will take a look at this problem.
Did I understand you correctly: with settings above the output of `ST: Execute` (ctrl+e ctrl+e) are fine but with `ST: Show Table Records` (ctrl+e ctrl+s) the output has shifted columns?

**Comment by mercurykd** [comment]
> Did I understand you correctly: with settings above the output of ST: Execute (ctrl+e ctrl+e) are fine but with ST: Show Table Records (ctrl+e ctrl+s) the output has shifted columns?
yep, and no utf-8 when my settings 
```
"mysql": {
            "options": ["-f", "--table","--default-character-set=utf8"],
        }
```

>  we use Plain Text syntax to show all other output, because Plain Text performs much better for long output

maybe add option in settings? desc table is short, but you must choose table...

do I create a issue?

**Comment by tkopets** [comment]
> desc table is short, but you must choose table...

For `ST: Describe Table` we are already using the SQL syntax.

As for `ST: Execute` why you would need SQL syntax if the output is usually not SQL?

**Comment by mercurykd** [comment]
> As for ST: Execute why you would need SQL syntax if the output is usually not SQL?

in the results tab, you can not write, therefore, it seems to me that it does not matter which syntax, but I want a color, pleasant for the eyes, separation

sorry for my bad english

**Comment by tkopets** [comment]
In Sublime Text syntax is what determines how to apply a color to an output.

I understand your request, but what you ask cannot be easily implemented.
* right now in Sublime Text there is no built-in syntax that would highlight a table output
* applying SQL syntax to non-SQL output makes things look even worse. See #84

**Comment by mercurykd** [comment]
I understand, and all the same sql-syntax is better than nothing (plaintext) imho

I often override the output of the results in csv, for later use with the advancedCSV extension, it allows me to format, sort and so on, very conveniently. Maybe in this direction it makes sense to think?

**Comment by mtxr** [comment]
I don't think that's a good idea for SQLTools. This is more related to CSV like extensions.

@mercurykd If you still facing some problems with syntax, could you please open a bug?

I'm closing this issue because it's not fully related with SQL stuff, ok? It's better if you create a new one in case of need.

Thank you for you suggestion!
