### ISSUE TITLE
Colored output in output panel

### ISSUE THREAD

**Issue by aditya43** [mtxr/SQLTools#161]
### Issue Type

Feature Request | Bug/Error | Question

### Description

Hello,

When I use CTRL+e, CTRL+d 
It shows me table description in a well formatted colored output :

![colored_output](https://user-images.githubusercontent.com/25119995/33586025-39c2a914-d98d-11e7-8c98-8d5ea4cfedc9.png)

But, when I run a query DESCRIBE `my_table`
It shows me table description in a plain text output format.

![plain_text_output](https://user-images.githubusercontent.com/25119995/33586026-3a0ac668-d98d-11e7-9337-34dcc11214e7.png)

Is it a bug or is there any workaround to get colored output when we execute queries?

Thank You

**Comment by tkopets** [comment]
This is not a bug, this output behavior is intentional.

`ST: Describe Table` and `ST: Describe Function` are using SQL syntax (if your main syntax is also SQL-related) because SQL is expected in the output, otherwise, we use Plain Text syntax to show all other output, because 90% of the case we don't expect valid SQL in the output but rather regular tabular data, applying SQL syntax to non-sql looks bad (think about unterminated string quotes and highlighting of random words in the output).
We used to apply SQL to all output before and I know it looks not very attractive as I'm a heavy SQLTools user myself.
`Plain Text` syntax performs much better for long output as well.
See related discussion #84

**Comment by aditya43** [comment]
Thanks
