### ISSUE TITLE
format sql(indents)

### ISSUE THREAD

**Issue by mercurykd** [mtxr/SQLTools#174]
- *sublime version*: 3156
- *SQLTools Version*: v0.9.7
- *OS*: Windows
![2018-01-17_00-58-29](https://user-images.githubusercontent.com/30900414/35012015-acb74ce4-fb21-11e7-842c-8a2cdfcea77a.jpg)

CTRL+E+B

![2018-01-17_00-59-08](https://user-images.githubusercontent.com/30900414/35012040-c11da372-fb21-11e7-8bcd-9d89e36de7a2.jpg)

**Comment by tkopets** [comment]
Thank you for reporting this issue!
Unfortunately, this issue is originating from the [sqlparse](https://github.com/andialbrecht/sqlparse) library which SQLTools is using to format SQL.
Feel free to submit this issue request to [sqlparse](https://github.com/andialbrecht/sqlparse) repo.
https://github.com/andialbrecht/sqlparse/issues
