### ISSUE TITLE
Broken result table in Windows

### ISSUE THREAD

**Issue by rustam-crunch** [mtxr/SQLTools#33]
FOA: Thanks a lot for your work!
In result pane formatting of output is broken **_See  attached image_**
This make ST using very inconvenient
 
![image](https://cloud.githubusercontent.com/assets/5345476/18932299/73312d92-85d8-11e6-9c08-8de702e20aa9.png)

**Comment by mtxr** [comment]
Hey @rustam-crunch!

The problem is the font you're using.
It's not a monospaced font. 

Check this link:
[](https://www.granneman.com/webdev/editors/sublime-text/configuring-sublime-text/)

It suggests this setting for monospaced font
```json
{
...
"font_face": "Consolas",
...
}
```

> I really like Microsoft's Consolas: it's a very readable, usable, thoughtful mono space font for coding. It should be on any recent Windows machine & any Mac that has Microsoft Office installed on it. If you don't have Consolas, I recommend the following instead:
> 
> Windows: Courier New (actually, if you're OK with downloading & installing fonts, I'd use Andale Mono instead)
> Mac OS X: Menlo or Courier
> Linux: DejaVu Sans Mono (if you don't have the DejaVu fonts, you can get them at DejaVu fonts)


I'm using Anonymous Pro as my mono spaced font. I like it, but you'll find one you enjoy coding with.

Hope it helps. :D



M.
