### ISSUE TITLE
Column Widths

### ISSUE THREAD

**Issue by boyxx001** [mtxr/SQLTools#54]
Is there any way to fix the column widths? Some columns are too wide for the results & the column name while some others are just wide enough for the results but cut off the column name.

Ideally a width based on the wider of either Column Name, or the results in the column.

![image](https://cloud.githubusercontent.com/assets/17655048/20399505/e20b63e0-acb6-11e6-80e9-4f868fa57c76.png)

**Comment by mtxr** [comment]
Hi @boyxx001!
 
SQLTools don't set columns automatically. It's defined by your cli settings (eg. ~/.psqlrc for postgresql or ~/.my.cnf for mysql).

Usually this cli tools select the wider value (of all rows) and set it as col width.

I hope I could help you a bit more, but you will need to Google it because I really don't know it xD

Hope you succeed!

I'm closing it now, ok?

M.
