### ISSUE TITLE
How use with remote host

### ISSUE THREAD

**Issue by denvut** [mtxr/SQLTools#74]
Hello.
Please help me, if you can.
How use with remote host?
I tried in console:
ssh -L 5162:localhost:5432 admin@172.16.0.162

In connection settings:
{
    "connections": {
        "Connection 2": {
            "type"    : "pgsql",
            "host"    : "127.0.0.1",
            "port"    :  5162,
            "username": "user",
            "password": "12567",
            "database": "base",
            "encoding": "utf-8"
        },
    },
    "default": "Connection 2"
}

in sublime console:
Traceback (most recent call last):
  File "/home/denis/.config/sublime-text-3/Packages/SQLTools/SQLTools.py", line 217, in <lambda>
    Window().show_quick_panel(menu, lambda index: ST.setConnection(index, tablesCallback, columnsCallback, functionsCallback))
  File "/home/denis/.config/sublime-text-3/Packages/SQLTools/SQLTools.py", line 202, in setConnection
    ST.loadConnectionData(tablesCallback, columnsCallback, functionsCallback)
  File "/home/denis/.config/sublime-text-3/Packages/SQLTools/SQLTools.py", line 189, in loadConnectionData
    ST.conn.getTables(tbCallback)
  File "/home/denis/.config/sublime-text-3/Packages/SQLTools/SQLToolsAPI/Connection.py", line 63, in getTables
    query = self.getOptionsForSgdbCli()['queries']['desc']['query']
  File "/home/denis/.config/sublime-text-3/Packages/SQLTools/SQLToolsAPI/Connection.py", line 162, in getOptionsForSgdbCli
    return self.settings.get('cli_options', {}).get(self.type)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by tkopets** [comment]
Most probably you have some kind of misconfiguration in your settings file `SQLTools.sublime-settings`.
Please paste a complete contents of your `SQLTools.sublime-settings` , otherwise it would be impossible to help you.

**Comment by tkopets** [comment]
@denvut
The problem is that SQLTools cannot find your DB cli binary (`mysql`, `psql`, `sqlite` etc) in PATH.
Either add your DB cli binaries to PATH or set the full path to you cli binary.
Example cli section from `SQLTools.sublime-settings` below:
```
    "cli" : {
        "psql"   : "/usr/lib/postgresql/9.3/bin/psql" ,
    }
```
The correct messaging will be available in next release.

SQLTools should work fine with tunneled connections, just make sure you have:
* `psql` in your path or full path to `psql` is specified in settings file
* make sure you have your [pgpass.conf](https://www.postgresql.org/docs/current/static/libpq-pgpass.htmll) configured for your connection

Please let us know if you still have issues.
