### ISSUE TITLE
Plain Text Syntax Highlighting in results window

### ISSUE THREAD

**Issue by heimer16** [mtxr/SQLTools#84]
I would propose making the results window default to plain text syntax highlighting for a couple of reasons.  One, the sql syntax highlighting gets messed up when there are apostrophes in text fields, and secondly, (and this is part of a general performance issue I have with large files with any syntax highlighting) is that loading the window and scrolling and selecting are sluggish and choppy on large result sets.  Swapping out the default syntax to plain text is much faster and more responsive.

Or, maybe turn this into a setting to be able to set or disable syntax highlighting in the results window

**Comment by tkopets** [comment]
Thanks for your feedback!
Indeed, formatting of query execution results with SQL syntax highlighting is probably not the best idea, and in fact, I myself pretty often encounter the problems with apostrophes and other weird highlighting of output because of this.

However, I wouldn't simply throw away SQL highlighting in output completely, as it is still very helpful to see syntax highlighting when used in combination with other features (Table Description & Function Description).
The experience may vary depending on RDBMS being used as different DB CLI outputs produce different results.

Given above I will make the changes as follows:
* when executing queries (`ST: Execute`), showing sample of table records (`ST: Show Table Records`), showing explain plan for query (`ST: Explain Plan`) the syntax of the output pane would be set to `Plain Text`
* when showing table description (`ST: Table Description`) and showing function definition (`ST: Function Description`) the syntax of the output pane would be set to syntax highlight of the current view (instead of hardcoded SQL syntax). This way, if people use custom syntax highlighting for their SQL code that one would be picked instead of generic SQL highlighter.

Thoughts/feedback on proposed solution are welcome.

**Comment by tkopets** [comment]
Made the changes as described above in 7fbad4db7552cc7071b91f8b29ed2c82173ccf29 and c624d3e4dd42b5587a79b59691acf041a70e9838.

**Comment by tkopets** [comment]
The changes will be available in next release.

**Comment by heimer16** [comment]
Seems to be working great!  Thanks!
